- pom.xml
That works. Tested in dev box.
Committed also the change for the geoserver plugin in its repository. Anyway, GTG.
> upgrade to geoserver 2.7.0

- .gitmodules
- src/extension/pom.xml
- src/main/pom.xml
@julian1 I didn't test if it works. However it does include all the jars.
> build with ncdfgenerator

- src/main/pom.xml
enable the web interface for WPS
> add wps security web modules

- src/extension/ncdfgenerator/pom.xml
- src/main/pom.xml
> ncdfgenerator version is now 1-0-0 in pom's

- src/extension/ncdfgenerator/src/main/java/au/org/emii/ncdfgenerator/Main.java
- src/extension/ncdfgenerator/src/main/java/au/org/emii/ncdfgenerator/NcdfEncoder.java
- src/extension/ncdfgenerator/src/main/java/au/org/emii/ncdfgenerator/NcdfEncoderBuilder.java
- src/extension/ncdfgenerator/src/main/java/au/org/emii/wps/NetcdfOutputProcess.java
Fixes https://github.com/aodn/geoserver-build/issues/45
It was previously quite easy for the portal to construct invalid WPS netcdf requests.
> CQL filter is now optional

- .travis.yml
- pom.xml
The former one is intermittently down atm.
> Switch to alternative boundless repo

- pom.xml
- src/extension/layer-filters/pom.xml
- src/extension/ncwms/src/main/java/au/org/emii/geoserver/wms/UrlIndexWfsHttp.java
- src/extension/wps/pom.xml
- src/extension/wps/src/main/java/au/org/emii/ncdfgenerator/DoubleValueEncoder.java
- src/main/pom.xml
Standardise compiler target version
> Fix test failure due to time zone issues

- src/extension/ncwms/pom.xml
- src/extension/ncwms/src/main/java/au/org/emii/geoserver/wms/Ncwms.java
- src/extension/ncwms/src/main/java/au/org/emii/geoserver/wms/UrlIndexInterface.java
- src/extension/ncwms/src/main/java/au/org/emii/geoserver/wms/UrlIndexWfsHttp.java
- src/extension/ncwms/src/test/java/au/org/emii/geoserver/wms/UrlIndexWfsHttpTest.java
Use json library from geoserver upstream
> Eliminate dependency on java8

- README.md
- src/main/pom.xml
- src/main/src/jetty/.gitignore
- src/main/src/jetty/context-sample.xml
- src/main/src/jetty/override-web.xml
- src/main/src/jetty/resources/changelog.xml
Looked at this while trying to work out how to test my wps changes locally.  
No test data included.  May add some as a part of my testing.
> Add postgres database support for jetty:run

- src/extension/wps/doc/NCDFGENERATOR_README.md
- src/extension/wps/doc/wps-acorn.xml
- src/extension/wps/doc/wps-gsla.xml
- src/extension/wps/doc/wps-srs.xml
- src/extension/wps/doc/wps-ts_timeseries.xml
- src/extension/wps/src/main/java/au/org/emii/wps/GoGoDuckProcess.java
- src/extension/wps/src/main/java/au/org/emii/wps/NetcdfOutputProcess.java
- src/extension/wps/src/main/java/au/org/emii/wps/NotifierProcess.java
- src/extension/wps/src/main/java/au/org/emii/wps/SubsetExceptionHandler.java
- src/extension/wps/src/main/java/au/org/emii/wps/SubsetOperation.java
- src/extension/wps/src/main/resources/applicationContext.xml
Return errors running gogoduck/ncdfgenerator subsets as an output rather than a ProcessException.
> Return errors performing subsets as an output

- src/main/src/main/webapp/WEB-INF/web.xml
Without that, there is no:
* csv-with-metadata-header
* HTTP 500 error codes
A better solution should be introduced as this can break easily on
version upgrades.
Fixes https://github.com/aodn/aodn-portal/issues/2079
> Reintroduce web.xml

- src/extension/layer-filters/src/main/java/au/org/emii/geoserver/extensions/filters/LayerFiltersService.java
- src/extension/layer-filters/src/main/resources/applicationContext.xml
This reverts commit 5be0c0400c82e710d7f32b328cd5c4dbb315a2fa.
Refer #2080 - requires content changes/additional work.
> Revert "Regex restriction for uniqueValues"

- src/extension/layer-filters/src/main/java/au/org/emii/geoserver/extensions/filters/LayerFiltersService.java
- src/extension/layer-filters/src/main/resources/applicationContext.xml
Reverts aodn/geoserver-build#101
Reopens https://github.com/aodn/aodn-portal/issues/2080
> Revert "Revert "Regex restriction for uniqueValues""

- src/extension/wps/doc/GOGODUCK_README.md
This should satisfy aodn/geoserver-config#320
> Minimal documentation for configuring GoGoDuck

- src/extension/wps/doc/wps-acorn.xml
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/CSVConverter.java
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/Converter.java
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuckConfig.java
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuckModule_srs.java
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/Main.java
- src/extension/wps/src/main/java/au/org/emii/wps/GoGoDuckProcess.java
Initial PR: executes on the command line.
TODO: testing as WPS module.
For review.
> Add csv point download option to gogoduck

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuckModule_srs.java
Fixes issue https://github.com/aodn/aodn-portal/issues/2173
> Remove wind_speed variables from requests causing aggregation to fail

- doc/gridded_data/pom.xml
- pom.xml
- src/extension/wps/src/test/resources/anmn_ts.xml
- src/extension/wps/src/test/resources/soop_sst_trajectory.xml
- src/main/pom.xml
- src/main/src/jetty/geoserver_data/workspaces/imos/geoserver/ts_timeseries/netcdf.xml
I actually wanted to target wps-gogoduck here. 
Instead I suspect it I uses the grails-gogoduck pages for status reporting. 
This at least covers the emii -> aodn changes in this repo making it easier to search.
> aodn branding #279

- src/extension/ncwms/src/main/java/au/org/emii/geoserver/wms/Ncwms.java
- src/extension/ncwms/src/main/java/au/org/emii/geoserver/wms/NcwmsConfig.java
- src/extension/ncwms/src/main/java/au/org/emii/geoserver/wms/UrlIndexFeatureSource.java
- src/extension/ncwms/src/test/java/au/org/emii/geoserver/wms/NcwmsConfigTest.java
- src/extension/ncwms/src/test/resources/ncwms.xml
Enables support for datasets containing multiple times such as CARS
> Include TIME selection in thredds ncwms requests

- pom.xml
now that problems with it have been resolved
> Switch back to official maven repository

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuckModule_srs_oc.java
Remove remapped LONGITUDE/LATITUDE variables and remove SRS variable list - it doesn't apply to SRS_OC
> Systest fix for aodn/aodn-portal#2234

- src/extension/wps/build-nco.sh
Required for https://github.com/aodn/chef-private/pull/1618
> Update NCO source URLs in line with go-go-duck repo

- src/extension/wps/src/main/java/au/org/emii/utils/GoGoDuckConfig.java
@jonescc  Tested locally! :smile:
> Updated config parameter

- src/extension/wps/src/main/java/au/org/emii/ncdfgenerator/AttributeValueParser.java
- src/extension/wps/src/main/java/au/org/emii/ncdfgenerator/CharValueEncoder.java
- src/extension/wps/src/main/java/au/org/emii/ncdfgenerator/NcdfEncoder.java
- src/extension/wps/src/main/java/au/org/emii/ncdfgenerator/README.md
- src/extension/wps/src/main/java/au/org/emii/wps/NetcdfOutputProcess.java
- src/extension/wps/src/test/java/au/org/emii/ncdfgenerator/GenerationIT.java
- src/extension/wps/src/test/resources/soop_sst_trajectory.xml
This is part of the task of fixing SOOP
> Reinstate integration tests for ncdfgenerator

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/FeatureSourceIndexReader.java
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/FileMetadata.java
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/IndexReader.java
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/URIList.java
- src/extension/wps/src/main/java/au/org/emii/utils/GoGoDuckConfig.java
- src/main/src/jetty/geoserver_data/wps/gogoduck.xml
Related [PR](https://github.com/aodn/geoserver-config/pull/386)
> Issue 2267

- src/extension/wps/src/main/java/au/org/emii/gogoduck/exception/NetCdfProcessingException.java
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/FileMetadata.java
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
Fixes https://github.com/aodn/aodn-portal/issues/2268
> fixes returning empty files

- pom.xml
> Add S3 Maven config

- src/main/src/main/webapp/WEB-INF/web.xml
Fixes [#2349](https://github.com/aodn/aodn-portal/issues/2349)
> Enabled request logging

- src/extension/core/src/main/java/au/org/emii/core/Config.java
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
Fixes [#2351](https://github.com/aodn/aodn-portal/issues/2351)
> Validating time, lat, lon and layer name

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
Fixes [#2345](https://github.com/aodn/aodn-portal/issues/2345)
> Readable file size

- pom.xml
- src/extension/wps/pom.xml
- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/FileMetadata.java
Fix for error `ERROR [hdf5.H5header] - bad version 72 at filePos 218874346`
> Updated to netcdf4 version 4.6.6

- src/extension/wps/src/main/java/au/org/emii/wps/GoGoDuckProcess.java
Fixes [#2357](https://github.com/aodn/aodn-portal/issues/2357)
> Fixed repeted error messages

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
- src/extension/wps/src/main/java/au/org/emii/utils/GoGoDuckConfig.java
- src/extension/wps/src/test/resources/aggregation-files/srs_sst_l3s_1d_ngt_gridded_url/gogoduck.xml
- src/main/src/jetty/geoserver_data/wps/gogoduck.xml
Fixes [#2359](https://github.com/aodn/aodn-portal/issues/2359)
Revert of [PR](https://github.com/aodn/geoserver-build/pull/167)
> Added file limit

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
Fixes [#2351](https://github.com/aodn/aodn-portal/issues/2351) based on @jonescc  comment.
> Passing error to the user

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
- src/extension/wps/src/main/java/au/org/emii/wps/GoGoDuckProcess.java
Fixes [#2364](https://github.com/aodn/aodn-portal/issues/2364)
> Improved logging and added informative error message for user

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
[#2348](https://github.com/aodn/aodn-portal/issues/2348)
> Improved logging and handling download faliure

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
@anguss00  I did some work on this one but forgot to put my face against it. Maybe you can use the code.
> Stopping file download on subsetting error

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
Reverts aodn/geoserver-build#186
> Revert "Stopping file download on subsetting error"

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
Fixes [#2342](https://github.com/aodn/aodn-portal/issues/2342) 
Related [PR](https://github.com/aodn/aodn-portal/pull/2356)
> Improve user error message

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/FileMetadata.java
Fixes [#2375](https://github.com/aodn/aodn-portal/issues/2375)
> Added point time series validation

- src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
Increases number of files which can be handled by gogoduck from 50000 up to over 150000 files more than enough for existing collections
Also reduces the amount of memory used (more could be done here).
> Make the most of the ncrcat stdin file list limit

- src/extension/wps/src/main/java/au/org/emii/download/DownloadConfig.java
- src/extension/wps/src/main/java/au/org/emii/download/ParallelDownloadManager.java
- src/extension/wps/src/main/java/au/org/emii/wps/GoGoDuckProcess.java
- src/extension/wps/src/test/java/au/org/emii/download/ParallelDownloadManagerTest.java
@bhasin85 - will need to rebuild javaduck-test branch and deploy to test instance after merge
> ParallelDownloadManager can manage the execution pool

- src/extension/wps/src/main/java/au/org/emii/aggregator/NetcdfAggregator.java
> Don't build unpacker overrides from template dataset over and over

- src/extension/wps/src/main/java/au/org/emii/wps/gogoduck/config/GoGoDuckConfig.java
Configured aggregation override templates were not being found
Would need to start up a configured geoserver instance to test this.  Leaving that for now...
> Correct xpath to templates element in gogoduck.xml

- src/extension/wps/src/main/java/au/org/emii/wps/GoGoDuckProcess.java
- src/extension/wps/src/main/java/au/org/emii/wps/gogoduck/parameter/SubsetParameters.java
- src/extension/wps/src/test/java/au/org/emii/wps/gogoduck/parameter/SubsetParametersTest.java
> Updated regex for time validation

- src/extension/wps/src/main/java/au/org/emii/wps/gogoduck/parameter/SubsetParameters.java
- src/extension/wps/src/test/java/au/org/emii/wps/gogoduck/parameter/SubsetParametersTest.java
> Updated time/lat/lon validation

- src/extension/layer-filters/src/main/java/au/org/emii/geoserver/extensions/filters/FilterConfigurationException.java
- src/extension/layer-filters/src/main/java/au/org/emii/geoserver/extensions/filters/LayerFilterConfigurationPage.java
- src/extension/layer-filters/src/main/java/au/org/emii/geoserver/extensions/filters/LayerPage.java
Display exceptions loading filter configuration page.  Also fix issue trying to enable a non-existant remove link when checking the checkbox against a layer on this page
> Fixes #136

- src/extension/ncwms/src/main/java/au/org/emii/geoserver/wms/Ncwms.java
related to https://github.com/aodn/aodn-portal/pull/2705
for https://github.com/aodn/backlog/issues/902
> Add or pass on User_Agent header from portal

- src/main/src/main/webapp/WEB-INF/web.xml
(By enabling for all GET requests)
> aodn/backlog#2745 - enable CORS for GetFeatureInfo requests

- src/extension/csv-with-metadata-header/pom.xml
Backlog item: https://github.com/aodn/backlog/issues/3062
> WSD - Pivot Prototype - User correct layer filters version

- src/extension/csv-with-metadata-header/src/main/java/au/org/emii/geoserver/wfs/response/CsvPivotedFeatureCollectionSource.java
Fixes https://github.com/aodn/issues/issues/1058
> Handle NULL values in JSON field when pivoting

- .github/workflows/test.yml
- src/extension/csv-with-metadata-header/src/main/java/au/org/emii/geoserver/wfs/response/CsvPivotedFeatureCollectionSource.java
Backlog item: https://github.com/aodn/backlog/issues/3426
> Handle nulls better in pivot fields

- src/extension/csv-with-metadata-header/src/main/java/au/org/emii/geoserver/wfs/response/CsvPivotedFeatureCollectionSource.java
Backlog item: https://github.com/aodn/backlog/issues/3426
> Use correct default when json col is null

- src/extension/csv-with-metadata-header/src/main/java/au/org/emii/geoserver/wfs/response/CSVWithMetadataHeaderOutputFormat.java
Reverts aodn/geoserver-build#319
Refer to discussion: https://github.com/aodn/issues/issues/1120
> Revert "wfs csv format dates"

- Dockerfile
https://imos-artifacts.s3.ap-southeast-2.amazonaws.com/builds/geoserver-build_build/3708-set-ubuntu20/1/artifacts/geoserver-0.0.0-imos.war
geoserver:
endpoint: geoserver-cmrose2.dev.aodn.org.au
password: c6134c1d86b1d20ba3c221f06b9f9b11
stack_integration:
geoserver_endpoint: http://geoserver-cmrose2.dev.aodn.org.au/geoserver
username: admin
> Set ubuntu 20

- Dockerfile
This will install the required maven version so the build will succeed on Jenkins
You can see the build succeeds here: https://build.aodn.org.au/view/build/job/geoserver-build_build/job/5351-maven-upgrade/
> maven version 3.9.6 required
