aodn/geoserver-build

src/extension/gogoduck/build-nco.sh

The go-go-duck repository might go sooner than later, so might as well import that script so it's safe.

Build NCO script from GoGoDuck repository

---

pom.xml
src/extension/geoserver-layer-filter-extension/pom.xml
src/extension/gogoduck/pom.xml
src/extension/ncdfgenerator/src/test/java/au/org/emii/ncdfgenerator/GenerationIT.java
src/extension/notifier/pom.xml

Minor modifications to get things a bit cleaner.
Notice I've also commented out the ncdfgenerator `GenerationIT` tests, this is because we should be able to run `mvn test install`.

More pom cleanups

---

src/extension/notifier/src/main/java/au/org/emii/wps/HttpNotifier.java
src/extension/notifier/src/main/java/au/org/emii/wps/NotifierProcess.java
src/extension/notifier/src/main/java/au/org/emii/wps/RetryingHttpNotifier.java
src/extension/notifier/src/main/java/au/org/emii/wps/SimpleHttpNotifier.java
src/extension/notifier/src/main/resources/applicationContext.xml
src/extension/notifier/src/test/java/au/org/emii/wps/NotifierProcessTest.java
src/extension/notifier/src/test/java/au/org/emii/wps/RetryingHttpNotifierTest.java
src/extension/notifier/src/test/java/au/org/emii/wps/SimpleHttpNotifierTest.java

This is an implementation of HTTP notification with retry functionality.
There is a new interface `HttpNotifier` which can be made more general (i.e. `Notifier`) later, as needed.
I had a think about how `maxNotificationAttempts` and `retryInterval` are injected and I think I'm okay with them being in the constructor like this. I don't think they should be properties with mutator methods (some good points were made about this issue in [this blog comment](http://blog.schauderhaft.de/2012/01/01/the-one-correct-way-to-do-dependency-injection/comment-page-1/#comment-4765)).

WPS notifier with retry

---

src/extension/layer-filters/src/main/java/au/org/emii/geoserver/extensions/filters/LayerFiltersService.java
src/extension/layer-filters/src/main/resources/applicationContext.xml

Allow restricting uniqueValues with a regex. By default allow only
layers with a _map suffix.

Regex restriction for uniqueValues

---

src/main/pom.xml

Geoserver can support SQL Server via the gt-jdbc-sqlserver plugin, but it also needs a JDBC driver. The two options are Microsoft's own driver, free to download but not redistributable, or jTDS (http://jtds.sourceforge.net/) which is LGPL'd.  This uses jtds.

Add MS SQL Server support via jtds

---

README.md
pom.xml
src/main/pom.xml

Any reason why we need to wait for this?  I can use it now.

enable jetty:run on main project

---

src/extension/wps/doc/response-notifier.xml
src/extension/wps/doc/wps-notifier.xml
src/extension/wps/src/main/java/au/org/emii/wps/NotifierProcess.java
src/extension/wps/src/main/java/au/org/emii/wps/StringRawDataXmlPPIO.java
src/extension/wps/src/main/resources/applicationContext.xml
src/extension/wps/src/test/java/au/org/emii/wps/NotifierProcessTest.java

Modified notifier process to return the response from the wrapped wps process so that the downloadable file or errors creating it are both accessible.
For example submitting: https://github.com/aodn/geoserver-build/blob/return-response/src/extension/wps/doc/wps-notifier.xml
Returns: https://github.com/aodn/geoserver-build/blob/return-response/src/extension/wps/doc/response-notifier.xml
Struggled with GeoServers WPS implementation somewhat:
a) using http://geoserver/wps in a reference href results in geoserver directly passing only one output from the called process to the calling process.  Useful for not streaming data via http but useless when trying to return two outputs
b) can't use RawData when using references  when not using http://geoserver/wps as the input stream is closed and so …

Modify notifier to return response from wrapped process

---

src/extension/wps/src/main/java/au/org/emii/notifier/HttpNotifier.java
src/extension/wps/src/main/java/au/org/emii/notifier/RetryingHttpNotifier.java
src/extension/wps/src/main/java/au/org/emii/notifier/SimpleHttpNotifier.java
src/extension/wps/src/main/java/au/org/emii/wps/AbstractNotifierProcess.java
src/extension/wps/src/main/java/au/org/emii/wps/GoGoDuckProcess.java
src/extension/wps/src/main/java/au/org/emii/wps/NetcdfOutputProcess.java
src/extension/wps/src/test/java/au/org/emii/notifier/RetryingHttpNotifierTest.java
src/extension/wps/src/test/java/au/org/emii/notifier/SimpleHttpNotifierTest.java

Allow portal to send correct email by including whether the subset succeeded or failed in the callback

Include whether subset succeeded or failed in portal callback

---

src/main/pom.xml

Geowebcache is a core plugin that we don't want - we use squid for caching and just having geowebcache installed adds minutes to the startup time.

Remove geowebcache plugin which is included by default in core geoserver

---

src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java

Redirect stderr to stdout. Otherwise it'll wait for process
indefinitely, until stderr is consumed.
Fixes #90

Prevent GoGoDuck from jamming

---

src/main/pom.xml
src/main/src/jetty/context-sample.xml

Use dbcp connection pooling as per tomcat setup so that connection pooling issues can be reproduced and investigated locally.
NB: this requires context.xml on local clones of this repository to be updated as per changes made to context-sample.xml to run mvn jetty:run after these changes.

Use dbcp connection pooling for mvn jetty:run

---

src/extension/ncwms/src/main/java/au/org/emii/geoserver/wms/UrlIndexFeatureSource.java

Return only local time, not a ISO8601 timestamp.

Fix timesteps call in ncwms controller

---

src/extension/ncwms/src/main/java/au/org/emii/geoserver/wms/UrlIndexFeatureSource.java
src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/FeatureSourceIndexReader.java
src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java
src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuckModule.java
src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/HttpIndexReader.java
src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/IndexReader.java
src/extension/wps/src/main/java/au/org/emii/wps/GoGoDuckProcess.java
src/extension/wps/src/main/resources/applicationContext.xml
src/extension/wps/src/test/java/au/org/emii/gogoduck/worker/GoGoDuckModuleTest.java

If used from the command line, GoGoDuck still uses regular WFS, but
when used as a WPS service, it'll use the provided Geoserver
catalog and query it, preventing another thread from spawning and
potentially causing a deadlock.

GoGoDuck can use Feature Source

---

pom.xml
src/extension/csv-with-metadata-header/pom.xml
src/extension/ncwms/pom.xml
src/extension/wps/pom.xml
src/main/pom.xml

Use matching gt-jdbc-sqlserver version
Use managed versions of joda-time and easymock
Use parent version for extensions so we don't have to update the version in multiple places (and fixes warnings for me in eclipse)

Upgrade to GeoServer 2.8.2

---

pom.xml
src/extension/ncwms/pom.xml
src/extension/wps/pom.xml
src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuckModule_cars.java
src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuckModule_cars_australia_weekly.java
src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuckModule_cars_world_monthly.java
src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/Main.java
src/extension/wps/src/main/java/au/org/emii/wps/GoGoDuckProcess.java
src/extension/wps/src/main/resources/applicationContext.xml

GoGoDuck URL mangling can be set from geoserver data dir. This is
not being set as a bean property any more and provides more
flexibility.
Also fix CARS URLs, so they point to the right place of CARS at
the moment on S3.
Fixes #117.

GoGoDuck URL mangling can be set from config

---

src/extension/wps/src/main/java/au/org/emii/ncdfgenerator/AttributeValueParser.java

1. Point to prod database
2. Point to geoserver-config
3. Replace geoserver-config/workspaces/imos/JNDI_soop_sst/soop_sst_nrt_trajectory_data with [netcdf.xml](https://github.com/aodn/geoserver-build/files/502099/netcdf.txt) @bpasquer  will make the geoserver-config changes for all the relevant records
**Sample Request**
```
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" service="WPS" version="1.0.0">
<ows:Identifier>gs:NetcdfOutput</ows:Identifier>
<wps:DataInputs>
<wps:Input>
<ows:Identifier>typeName</ows:Identifier>
<wps:Data>
<wps:LiteralData>imos:soop_sst_nrt_trajectory_data</wps:LiteralData>
</wps:Data> …
```

Handling empty values in template ''

---

src/extension/wps/src/main/java/au/org/emii/wps/GoGoDuckProcess.java

So that it is cleaned up after it is copied to the output artifacts directory
(Current storing gogoduck output twice)

Use temporary resource for gogoduck output

---

pom.xml

Moved Maven repo to content.aodn.org.au for S3 consolidation.

Move Maven repo to content.aodn.org.au bucket

---

pom.xml

Requires https://github.com/aodn/geoserver/pull/14 to be merged and built in jenkins before this can be built.

Use 2.8.4-IMOS-SNAPSHOT

---

src/extension/wps/pom.xml
src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java

Instead of passing the files to be aggregated on the command line (limited to 2232)
pass the files to be aggregated on stdin which has no such limit.

Allow more than 2232 files to be aggregated

---

src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java

@jonescc As I understand it, this should remove the tmp file creation

Add '--no_tmp_fl' argument to ncrcat aggregate command

---

src/extension/ncwms/src/main/java/au/org/emii/geoserver/wms/Ncwms.java

@jonescc 
Fixes systest VIT. Thredds version 1.3.0 was expecting CRS to be included as a parameter, proxied requests were throwing 400s (!) as a result

Pass thredds version specified in the metadata record

---

src/extension/layer-filters/src/main/java/au/org/emii/geoserver/extensions/filters/LayerFiltersService.java

Allow workspace and layer name to be specified together in a single parameter (but still accept old way as well). Return a content-type so we're conforming to web standards and so geowebcache doesn't get whiney

EnabledFilters Extension: Merge workspace and layer parameters

---

src/extension/wps/src/main/java/au/org/emii/aggregator/NetcdfAggregator.java
src/extension/wps/src/main/java/au/org/emii/aggregator/coordsystem/LatLon2D.java
src/extension/wps/src/main/java/au/org/emii/aggregator/index/IndexChunk.java
src/extension/wps/src/main/java/au/org/emii/aggregator/index/IndexChunkIterator.java
src/extension/wps/src/main/java/au/org/emii/aggregator/variable/AbstractVariable.java
src/extension/wps/src/test/java/au/org/emii/aggregator/index/IndexChunkIteratorTest.java

Use an IndexChunkIterator using long 1D offsets to read/write variable values one chunk of values at a time instead of ChunkingIndex which doesn't.

Fixes #256.   

---

pom.xml
src/extension/wps/pom.xml

This dependency includes old versions of libraries such as the aws sdk's which causes issues for clients that use it.
Required change to go with https://github.com/aodn/netcdf-iterator/pull/6

Remove use of problematic shaded netcdfAll dependency

---

src/aggregator/src/main/java/au/org/emii/aggregator/dataset/AbstractNetcdfDataset.java
src/aggregator/src/main/java/au/org/emii/aggregator/dataset/SubsettedDataset.java
src/aggregator/src/main/java/au/org/emii/aggregator/template/TemplateDataset.java
src/extension/wps/src/main/java/au/org/emii/wps/gogoduck/parameter/SubsetParameters.java
src/extension/wps/src/test/java/au/org/emii/wps/gogoduck/parameter/SubsetParametersTest.java

Linked PR https://github.com/aodn/aws-wps/pull/224
Implements depth (z dimension) as a ucar Range of monotonically increasing integers (based on the skeleton in aws-wps for handling z dimenion.
CARS datasets represent depth as a short variable, which is converted into a Range here (comments  and feedback on this conversion please).
Requires passing `DEPTH,0.0,100.0` as an addition to the subset; can be non-existant, in which case a null z-dimension is added to the subset.

Prototype for z (depth) parameter subsetting

---

src/aggregator/src/main/java/au/org/emii/aggregator/template/TemplateDataset.java

If z-dim exists, and a subset is not provided, use the max and min z-dimension of the dataset

Only apply depth aggregation overrides where a z-dim exists

---

src/extension/wps/src/main/java/au/org/emii/ncdfgenerator/NcdfEncoder.java
src/extension/wps/src/test/resources/anmn_ts.xml

Was throwing an exception when an attribute sql query returned no results.
Added a check to see if any records are returned before trying to return a value.
A null value is checked before adding the attribute to the file by existing code, and the end result will be that the attribute will not be added to the output file and the missing attribute will be logged.

Fixes aodn/aodn-portal#2652

---

src/extension/ncwms/src/main/java/au/org/emii/geoserver/wms/SimpleKvpParser.java
src/extension/ncwms/src/main/resources/applicationContext.xml

Don't override the core PaletteKvpParser bean definition as this requires
context files to be loaded in the right order for it to work and this is outside our control
Instead use a simple parser which just returns the provided string for ncwms PALETTE request parameters

Addresses aodn/backlog#941

---

src/main/pom.xml

~~Note: https://github.com/aodn/geoserver-build/pull/287 the plugin version will need to be updated to align with the Geoserver version if this PR is merged first~~

Re-enable Geowebcache with S3 support

---

pom.xml

If there is no config, this module is not activated at Geoserver startup.
An example configuration file is in a draft PR: https://github.com/aodn/geoserver-config/pull/615, but this should probably be provisioned during deployment, since the values should be tuned based on the environment capacity.

Add Control Flow extension to dependencies

---

src/main/pom.xml

I needed this for local builds. I'm not sure how this could impact anything else, but it was required for me to be able to run it locally

Update jetty for local builds

---

.github/workflows/test.yml
.travis.yml
pom.xml

For https://github.com/aodn/issues/issues/940
It's failing in the same way as the travis build is: ```Error:  Non-resolvable import POM: Could not transfer artifact org.geoserver:geoserver:pom:2.15.0 from/to mvnrepository (http://mvnrepository.com/artifact/): Authorization failed for http://mvnrepository.com/artifact/org/geoserver/geoserver/2.15.0/geoserver-2.15.0.pom 403 Forbidden @ line 29, column 25```
Since this task is just to lift and shift travis builds to github actions I think we'll have to just accept it like that.

Replace Travis CI with Github Actions
